projects/Matrix.json

added an entry for matrix.org based on the template.

added Matrix entry

---

projects/UBOS.json

Not sure the Ohloh Id is correct. They seem to have gone to text identifiers. And BTW, it's not called ohloh any more either :-)

Added UBOS

---

projects/Shark.json

I added the [Shark framework](https://sharksystem.net) to the list of technologies.
Cheers

Added Shark to projects

---

projects/Lighthouse.json

I noticed that Lighthouse was not on the list of projects yet, and I believe it belongs here.

Add Lighthouse

---

projects/SwellRT.json

Add [SwellRT](http://swellrt.org), to the list of projects.

SwellRT project added

---

projects/searx.json

code is on https://github.com/asciimoo/searx

addition of "searx" A privacy-respecting, hackable metasearch engine

---

css/main.scss
index.html

* Use flexbox to make the page a little easier to follow.

Style changes for pages:

---

projects/Alexandria.json

I've added a new project called the "Distributed Library of Alexandria" that aims to allow monetization of efficient distribution systems (like P2P) as well as create a resilient network for publishing content. It was recently covered on the Steal This Show Podcast - really interesting :).

Added project 'Distributed Library of Alexandria'

---

projects/GUN.json

Adds project JSON for https://github.com/amark/gun

Add GUN project

---

projects/Synereo.json

This is my own description of Synereo and is being reviewed by the Synereo team.
I hope it is not too long...

add Synereo.json

---

projects/PrivMX.json

Hi, 
I'd like to propose a new entry for the database. PrivMX WebMail is pubilcly available for a month...
kind regards,
MM

PrivMX WebMail information

---

projects/BitDust.json

Hi. Would like to contribute my project to this list: http://bitdust.io. I was very happy to find so much related projects, thanks for your activity!

add   projects/BitDust.json

---

projects/Ethereum.json

Correcting Ethereum project link.

correcting Ethereum project link

---

README.md

On my "quest" to find a well suited way to implement p2p I stumbled across this page and later on OpenDHT. Think it makes a valuable addition to this collection.

Add OpenDHT

---

README.md

Add `AKASHA.world` to `Social Networks`

Add AKASHA.world

---

README.md

Was https://github.com/redecentralize/alternative-internet/pull/226

Add from previous PR

---

README.md

Added UBOSbox Nextcloud

---

README.md

The | state-of-the-art | secure-by-default | one-touch-deployed | XMPP server for everyone.
This is the project I've been working on for the last year and a half and is now rather mature, with automated S3 nightly encrypted backups and a simple to use clusterization tool.
Thanks!

Added aenigma

---

README.md

Add DAOstack

---

README.md

As one of the original founders of Project Byzantium, I can tell you with certainty that the project is long dead. It has not been maintained in over 5 years. None of the core developers have any interest in reviving it. There are known bugs and security vulnerabilities which will not be fixed.

mark Project Byzantium as dead

---

README.md

Cloudbank project is new age cryptocurrency.

cloudbank has been added.

---

README.md

Project at https://github.com/MichaelMure/git-bug

Add git-bug

---

README.md

not sure which link to add. Github is here: https://github.com/irislib/iris/blob/master/README.md

add Iris social network

---

README.md

Add git-dit, the distributed issue tracker for git.

Add git-dit

---

README.md

For more information, check out the FAQ page: https://kevacoin.org/faq.html

Added Kevacoin key-value database.

---

README.md

Please add the Internet of People project to the listing.

Add Internet of People

---

README.md

This MR adds Sia and Skynet to the list of decentralized cloud storage solutions.

Add Sia and Skynet to Cloud storage options

---

README.md

They're a promising platform supported by the same folks making PeerTube!

add Mobilizon

---

README.md

closes #304 
added CodiMD collaborative editor

codimd added, Etherpad uppercase

---

README.md

Adding an "Identity" category into `A collection of interesting networks and technology aiming at re-decentralizing the Internet.`

Add item for decentralized identity

---

README.md

Fixed link to IOP Community site

---

README.md

Adding the libreweb.org project.

Add LibreWeb

---

README.md

Last commits to Telehash are several years old

Formatting + declare Telehash possibly dead

---

README.md

gittorrent.org doesn't resolve

Declare gittorrent apparently dead

---

README.md

add db3 network

---

README.md

Grassroots open protocol for per-user storage on the Web https://remotestorage.io

Add remoteStorage

---

README.md

Open source protocol for serverless, adminless, decentralized social media applications based on communities https://plebbit.com

Add plebbit
